name: "Is User a Member of any Team"
description: |
  This action will take the username and a list of team names in format <org>/<team>
  And then perform an api Query to fetch the team metadata and evaluate whether the user
  is a member of any of them.

  Then it will set a boolean result as output
inputs:
  token:
    description: "Github Api token with repo scope, e.g. secrets.GITHUB_TOKEN"
    required: true
  username:
    description: |
      Username of the github user to check: anyuser3445
      Can also be comma separated list of users user1,user2

      This action returns true if any user is a member of any team
      First match results to true
    required: true
  teams:
    description: "Comma-sparated list of teams to check membership: org/team1,org/team2"
    required: true
  varName:
    description: "If given, then action will export the result as this env Var"
    required: false
    default: USER_IS_MEMBER
outputs:
  ismember:
    description: "true if user is member of one or more teams"
  userName:
    description: Username of the first found user who is member of a team 
  teamName:
    description: Team name in case the user's team was found
runs:
  using: node16
  main: dist/index.js
